apiVersion: v1
kind: Service
metadata:
  name: packetstreamer-receiver
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "packetstreamer-receiver.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    {{- include "packetstreamer-receiver.selectorLabels" . | nindent 4 }}